services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    image: angular-calendar
    ports:
      - "4200:4200"
    develop:
      watch:
        - action: sync
          path: .
          target: /app