apiVersion: v1
kind: Service
metadata:
  name: angular-frontend
spec:
  type: NodePort
  selector:
    app: angular-frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 32000