---
apiVersion: v1
kind: Service
metadata:
  name: calendarapp-service
  labels:
    app: calendarapp
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 4200
    nodePort: 30002
    protocol: TCP
  selector:
    app: calendarapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendarapp-deployment
  labels:
    app: calendarapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calendarapp
  template:
    metadata:
      labels:
        app: calendarapp
    spec:
      containers:
      - name: angular-frontend
        image: arrow02/angular-calendar:v1
        ports:
        - containerPort: 4200
---