apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: event-store
  name: event-store
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: event-store
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: event-store
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: event_store
            - name: MYSQL_ROOT_PASSWORD_FILE
              value: /run/secrets/db-password
          image: mysql:8.0
          name: event-store
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets
              name: db-password
              subPath: db-password
            - mountPath: /var/lib/mysql
              name: db-data
            - mountPath: /docker-entrypoint-initdb.d
              name: event-store-cm1
      restartPolicy: Always
      volumes:
        - name: db-password
          secret:
            items:
              - key: db-password
                path: db-password
            secretName: db-password
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
        - configMap:
            name: event-store-cm1
          name: event-store-cm1
