apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: link-provider
  name: link-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: link-provider
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: link-provider
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: event-store
            - name: DB_NAME
              value: event_store
            - name: DB_PORT
              value: "3306"
            - name: EVENT_VIEW_URL
              value: http://localhost:4200/signup
          image: link-provider
          name: link-provider
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets
              name: db-user
              subPath: db-user
            - mountPath: /run/secrets
              name: db-password
              subPath: db-password
            - mountPath: /link-provider/app
              name: link-provider-cm0
      restartPolicy: Always
      volumes:
        - name: db-user
          secret:
            items:
              - key: db-user
                path: db-user
            secretName: db-user
        - name: db-password
          secret:
            items:
              - key: db-password
                path: db-password
            secretName: db-password
        - configMap:
            name: link-provider-cm0
          name: link-provider-cm0
